version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: firstTradeUnion
    volumes:
      - ${PWD}/data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - tradeUnionNetwork

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ${PWD}/data/redis:/data
    command: redis-server  --appendonly yes
    networks:
      - tradeUnionNetwork

  api:
    container_name: api
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - db
      - redis
    networks:
      - tradeUnionNetwork

  client:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3500:3500'
    depends_on:
      - api
    networks:
      - tradeUnionNetwork

networks:
  tradeUnionNetwork:
